version: '3.3'
services:

  frontend:
    build:
        context: ../../
        dockerfile: ./docker/dev/Dockerfile
    ports:
        - 127.0.0.1:8080:8080
    volumes:
        - ../../:/app/
    entrypoint:
        - /docker-entrypoint.sh
